# Generated by Django 4.2.2 on 2023-06-29 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Orden_Salida',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cant_Art_Salida', models.IntegerField()),
                ('fecha_Salida', models.DateTimeField()),
                ('codigo_Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.articulo')),
                ('codigo_Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Pedido',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cant_Solicitada', models.IntegerField()),
                ('fecha_Solicitud', models.DateTimeField()),
                ('codigo_Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.articulo')),
                ('codigo_Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Ingreso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cant_Art_Ingresados', models.IntegerField()),
                ('fecha_Ingreso', models.DateTimeField()),
                ('codigo_Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.articulo')),
                ('codigo_Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='codigo_Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='codigo_Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.marca'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='codigo_Modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.modelo'),
        ),
    ]
