# Generated by Django 4.2.2 on 2023-06-29 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0002_articulo_categoria_marca_modelo_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_ingreso',
            name='codigo_Usuario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Almacen.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden_pedido',
            name='codigo_Usuario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Almacen.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden_salida',
            name='codigo_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.usuario'),
        ),
    ]
