# Generated by Django 4.2.2 on 2023-07-05 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0003_alter_orden_ingreso_codigo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_ingreso',
            name='hora_Ingreso',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden_pedido',
            name='hora_Solicitud',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden_salida',
            name='hora_Salida',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden_ingreso',
            name='fecha_Ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orden_pedido',
            name='fecha_Solicitud',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orden_salida',
            name='fecha_Salida',
            field=models.DateField(),
        ),
    ]
